### ISSUE TITLE
Home Assistant logs do not include stracktraces

### ISSUE THREAD

**Issue by anton-johansson** [anton-johansson/home#49]
I need a multiline parser here, and a unit test to cover that.

Example:
```
2018-11-04 22:00:00 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/sensor/speedtest.py", line 166, in update
    speed.get_servers(servers)
  File "/usr/local/lib/python3.6/site-packages/speedtest.py", line 1288, in get_servers
    raise NoMatchedServers()
speedtest.NoMatchedServers
```

Each line here was logged separately, and only the first one actually got a severity etc.

**Comment by anton-johansson** [comment]
Maybe fix #40 first.

**Comment by anton-johansson** [comment]
There seems to be stack traces without a "real" log (i. e. logs without date, severity, thread and name for example. See:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/pysonos/events.py", line 457, in run
    sub.renew()
  File "/usr/local/lib/python3.6/site-packages/pysonos/events.py", line 567, in renew
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: http://<ip-address>:1400/MediaRenderer/AVTransport/Event
```

I assume these are uncaught exceptions or something like that.

**Comment by anton-johansson** [comment]
Closing in favor of #66.
