### ISSUE TITLE
Speedtest logs errors

### ISSUE THREAD

**Issue by anton-johansson** [anton-johansson/home#50]
```
2018-11-04 22:00:00 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/sensor/speedtest.py", line 166, in update
    speed.get_servers(servers)
  File "/usr/local/lib/python3.6/site-packages/speedtest.py", line 1288, in get_servers
    raise NoMatchedServers()
speedtest.NoMatchedServers
```

**Comment by anton-johansson** [comment]
Not having this problem anymore. I think I changed server ID a few months back.

**Comment by iainp999** [comment]
Hi, sorry to dive in here but I found your issue via google.

After a bit of digging in the code, it seems that the speedtest package grabs a list of servers to ignore from https://www.speedtest.net/speedtest-config.php 

It's near the top, "ignoreids"

Basically, if you pick an ID in that list, chances are you'll get the NoMatchedServers exception.

Just thought I'd comment in case anyone else found themselves here!  Thanks.
